//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hello_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseLecturers
    {
        public string CourseId { get; set; }
        public string LecturesId { get; set; }
        public short LecturesOrder { get; set; }
        public decimal Share { get; set; }
    }
}
