//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hello_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        public string CourseId { get; set; }
        public string CourseName { get; set; }
        public string Type { get; set; }
        public string FacultId { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<decimal> Marks { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public short Contract { get; set; }
    }
}
