//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hello_Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesCourses : DbContext
    {
        public EntitiesCourses()
            : base("name=EntitiesCourses")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CourseLecturers> CourseLecturers { get; set; }
        public virtual DbSet<Courses> Courses { get; set; }
        public virtual DbSet<Email> Email { get; set; }
        public virtual DbSet<Faculties> Faculties { get; set; }
        public virtual DbSet<Lecturers> Lecturers { get; set; }
        public virtual DbSet<Ratings> Ratings { get; set; }
    }
}
