//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class courses
    {
        public string course_id { get; set; }
        public string course_name { get; set; }
        public string type { get; set; }
        public string facl_id { get; set; }
        public Nullable<int> size { get; set; }
        public Nullable<decimal> marks { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<System.DateTime> begin_date { get; set; }
        public short contract { get; set; }
    }
}
