//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesDBEntities : DbContext
    {
        public EntitiesDBEntities()
            : base("name=EntitiesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<course_lecturers> course_lecturers { get; set; }
        public virtual DbSet<courses> courses { get; set; }
        public virtual DbSet<email> email { get; set; }
        public virtual DbSet<faculties> faculties { get; set; }
        public virtual DbSet<lecturers> lecturers { get; set; }
        public virtual DbSet<ratings> ratings { get; set; }
    }
}
